/** AUTO-GENERATED by tools/generate-wgsl-layouts.mjs */
export const CASCADE_UNIFORMS_BYTE_SIZE = 144;

/** Field byte offsets within the WGSL `struct CascadeUniforms` (probeRayCast.wgsl.ts). */
export const CascadeUniformsOffset = {
  probeOriginWorld: 0,
  _pad0: 12,
  roomSize: 16,
  _pad1: 28,
  probeCount: 32,
  raysPerProbe: 44,
  rayGridSize: 48,
  intervalNear: 52,
  intervalFar: 56,
  cascadeIndex: 60,
  sunDirection: 64,
  sunAngularRadius: 76,
  sunColor: 80,
  envIntensity: 92,
  frameSeed: 96,
  lastCascade: 100,
  triIntersectEpsilon: 104,
  bvhMode: 108,
  tlasNodeCount: 112,
  emitterCount: 116,
  lightCount: 120,
  sunCastShadowDisabled: 124,
  _pad4: 128,
  _pad5: 132,
} as const;
