// Shared fixtures for the T2-B byte-identity goldens (test + capture harness).
// Representative material touching every mapped field / thin-film / spectral /
// layer-normal path, plus one plain material and all 5 analytic light kinds.

import type { MaterialSpec, SceneEmitter } from '@vitrum/core';

export const H = {
  baseColor: {},
  metallic: {},
  roughness: {},
  transmission: {},
  emissive: {},
  normal: {},
  alpha: {},
  clearcoat: {},
  clearcoatRoughness: {},
  clearcoatNormal: {},
  sheenColor: {},
  sheenRoughness: {},
  iridescence: {},
  iridescenceThickness: {},
  specularColor: {},
  specularIntensity: {},
  ao: {},
  lightMap: {},
  bump: {},
  anisotropy: {},
  thickness: {},
  frontNormal: {},
  backNormal: {},
} as const;

export const layerOf = new Map<unknown, number>([
  [H.baseColor, 3],
  [H.metallic, 4],
  [H.roughness, 5],
  [H.transmission, 6],
  [H.emissive, 7],
  [H.normal, 8],
  [H.alpha, 9],
  [H.clearcoat, 10],
  [H.clearcoatRoughness, 11],
  [H.clearcoatNormal, 12],
  [H.sheenColor, 13],
  [H.sheenRoughness, 14],
  [H.iridescence, 15],
  [H.iridescenceThickness, 16],
  [H.specularColor, 17],
  [H.specularIntensity, 18],
  [H.ao, 19],
  [H.lightMap, 20],
  [H.bump, 21],
  [H.anisotropy, 22],
  [H.thickness, 23],
  [H.frontNormal, 24],
  [H.backNormal, 25],
]);

const tform = (n: number) => ({
  scale: [n + 0.1, n + 0.2] as [number, number],
  offset: [n * 0.01, n * 0.02] as [number, number],
  rotation: n * 0.1,
});

export const richMaterial: MaterialSpec = {
  baseColor: [0.2, 0.4, 0.6],
  metallic: 0.3,
  roughness: 0.55,
  ior: 1.45,
  transmission: 0.7,
  emissive: [0.9, 0.1, 0.05],
  emissiveIntensity: 2.5,
  normalScale: 0.8,
  clearcoat: 0.4,
  clearcoatRoughness: 0.2,
  clearcoatNormalScale: 0.6,
  sheen: 0.5,
  sheenColor: [0.7, 0.3, 0.2],
  sheenRoughness: 0.35,
  iridescence: 0.6,
  iridescenceIor: 1.35,
  iridescenceThicknessRange: [120, 380],
  specularColor: [0.8, 0.85, 0.9],
  specularIntensity: 0.75,
  anisotropy: 0.4,
  anisotropyRotation: 0.3,
  attenuationColor: [0.9, 0.8, 0.7],
  attenuationDistance: 2.5,
  thickness: 0.5,
  opacity: 0.9,
  alphaMode: 'mask',
  alphaCutoff: 0.4,
  envMapIntensity: 1.2,
  aoMapIntensity: 0.85,
  lightMapIntensity: 1.1,
  bumpScale: 0.9,
  scatteringCoefficientRGB: [0.3, 0.4, 0.5],
  scatteringAnisotropy: 0.2,
  dispersionAbbeNumber: 40,
  shadingModel: 'unlit',
  spectralAttenuation: {
    wavelengthStart: 400,
    wavelengthEnd: 700,
    values: new Float32Array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]),
  },
  thinFilmStack: {
    incidentIor: 1.1,
    angleDependent: true,
    layers: [
      { ior: 1.3, thicknessNm: 200, extinctionCoefficient: 0.01 },
      { ior: 1.6, thicknessNm: 350, extinctionCoefficient: 0.02 },
      { ior: 2.0, thicknessNm: 120, extinctionCoefficient: 0.03 },
    ],
  },
  frontLayer: {
    transmission: [0.9, 0.8, 0.7],
    roughness: 0.25,
    normalScale: 0.7,
    normalMap: { handle: H.frontNormal, texCoord: 1, transform: tform(30) },
  },
  backLayer: {
    transmission: [0.6, 0.5, 0.4],
    roughness: 0.45,
    normalScale: 0.3,
    normalMap: { handle: H.backNormal, texCoord: 0, transform: tform(31) },
  },
  baseColorMap: {
    handle: H.baseColor,
    texCoord: 1,
    transform: tform(0),
    wrapS: 'clamp-to-edge',
    wrapT: 'mirrored-repeat',
    magFilter: 'linear',
    minFilter: 'nearest',
    mipFilter: 'linear',
  },
  metallicMap: { handle: H.metallic, transform: tform(1), wrapS: 'mirrored-repeat' },
  roughnessMap: { handle: H.roughness, transform: tform(2), minFilter: 'linear' },
  transmissionMap: { handle: H.transmission, transform: tform(3) },
  emissiveMap: { handle: H.emissive, texCoord: 1, transform: tform(4) },
  normalMap: { handle: H.normal, transform: tform(5) },
  alphaMap: { handle: H.alpha, transform: tform(6) },
  clearcoatMap: { handle: H.clearcoat, transform: tform(7) },
  clearcoatRoughnessMap: { handle: H.clearcoatRoughness, transform: tform(8) },
  clearcoatNormalMap: { handle: H.clearcoatNormal, transform: tform(9) },
  sheenColorMap: { handle: H.sheenColor, transform: tform(10) },
  sheenRoughnessMap: { handle: H.sheenRoughness, transform: tform(11) },
  iridescenceMap: { handle: H.iridescence, transform: tform(12) },
  iridescenceThicknessMap: { handle: H.iridescenceThickness, transform: tform(13) },
  specularColorMap: { handle: H.specularColor, transform: tform(14) },
  specularIntensityMap: { handle: H.specularIntensity, transform: tform(15) },
  aoMap: { handle: H.ao, texCoord: 1, transform: tform(16) },
  lightMap: { handle: H.lightMap, transform: tform(17) },
  bumpMap: { handle: H.bump, transform: tform(18) },
  anisotropyMap: { handle: H.anisotropy, transform: tform(19) },
  thicknessMap: { handle: H.thickness, transform: tform(20) },
};

export const plainMaterial: MaterialSpec = {
  baseColor: [1, 1, 1],
  roughness: 0.5,
  metallic: 0,
};

export const emitters: SceneEmitter[] = [
  {
    id: 'rect',
    kind: 'rect-area',
    color: [0.2, 0.4, 0.6],
    intensity: 5,
    position: [-1, 0, 1],
    uAxis: [2, 0, 0],
    vAxis: [0, 3, 0],
  },
  {
    id: 'disc',
    kind: 'disc-area',
    color: [0.9, 0.8, 0.7],
    intensity: 4,
    position: [2, 1, 0],
    normal: [0, 0, 1],
    radius: 1.5,
  },
  {
    id: 'spot',
    kind: 'spot',
    color: [1, 0.5, 0.25],
    intensity: 6,
    position: [0, 5, 0],
    direction: [0, -1, 0],
    angle: 0.6,
    penumbra: 0.2,
    decay: 2,
    distance: 12,
    castShadow: false,
  },
  {
    id: 'point',
    kind: 'point',
    color: [0.5, 0.25, 0.75],
    intensity: 2,
    position: [1, 2, 3],
    decay: 2,
    distance: 10,
  },
  {
    id: 'dir',
    kind: 'directional',
    color: [1, 1, 1],
    intensity: 3,
    direction: [0, 1, 0],
    angularDiameter: 0.05,
  },
];
