import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';

import { RESERVOIR_PT_HERO_WGSL } from '../wgsl/pathTrace/reservoirPtHero.wgsl.js';
import { RESTIR_PT_PRODUCER_WGSL } from '../wgsl/pathTrace/restirPtProducer.wgsl.js';
import { RESTIR_PT_RESOLVE_WGSL } from '../wgsl/pathTrace/restirPtResolve.wgsl.js';

interface SpecialtyCase {
  readonly id: string;
  readonly activeLobes: readonly string[];
  readonly reference: {
    readonly pdfSrc: number;
    readonly pHat: number;
    readonly wCandidate: number;
    readonly W: number;
  };
  readonly basePath: {
    readonly luminance: number;
  };
  readonly restirPt: {
    readonly luminance: number;
  };
  readonly ab: {
    readonly absDiff: number;
    readonly relativeError: number;
    readonly lobeDeltaFromNeutral: number;
  };
}

interface SpecialtyFixture {
  readonly schema: string;
  readonly mode: string;
  readonly coverage: {
    readonly specialtyLobes: readonly string[];
    readonly requiresGpuRecapture: boolean;
  };
  readonly summary: {
    readonly caseCount: number;
    readonly maxAbsoluteError: number;
    readonly maxRelativeError: number;
    readonly luminanceChecksum: number;
    readonly pdfChecksum: number;
  };
  readonly cases: readonly SpecialtyCase[];
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const fixturePath = resolve(repoRoot, 'tools/radiometric-ab/results-restir-pt-specialty.json');
const harnessPath = resolve(repoRoot, 'tools/radiometric-ab/ab-restir-pt-specialty.mjs');

function readFixture(): SpecialtyFixture {
  return JSON.parse(readFileSync(fixturePath, 'utf8')) as SpecialtyFixture;
}

describe('ReSTIR-PT specialty-lobe CPU/static reference', () => {
  const fixture = readFixture();

  it('keeps the checked-in fixture generated by the deterministic harness', async () => {
    const mod = (await import(pathToFileURL(harnessPath).href)) as {
      runRestirPtSpecialtyReference: () => SpecialtyFixture;
    };

    expect(mod.runRestirPtSpecialtyReference()).toEqual(fixture);
  });

  it('pins the one-sample producer/finalize/resolve identity for specialty lobes', () => {
    expect(fixture.schema).toBe('vitrum.restir-pt.specialty-reference.v1');
    expect(fixture.mode).toBe('cpu-static');
    expect(fixture.coverage.requiresGpuRecapture).toBe(false);
    expect(fixture.summary).toEqual({
      caseCount: 3,
      maxAbsoluteError: 0,
      maxRelativeError: 0,
      luminanceChecksum: 3.182546428591,
      pdfChecksum: 3.447061984901,
    });

    for (const c of fixture.cases) {
      expect(c.reference.pdfSrc, `${c.id} pdfSrc`).toBeGreaterThan(0);
      expect(c.reference.pHat, `${c.id} pHat`).toBeGreaterThan(0);
      expect(c.reference.wCandidate, `${c.id} wCandidate`).toBeCloseTo(
        c.reference.pHat / c.reference.pdfSrc,
        10,
      );
      expect(c.reference.W, `${c.id} W`).toBeCloseTo(1 / c.reference.pdfSrc, 10);
      expect(c.restirPt.luminance, `${c.id} restir/base luminance`).toBeCloseTo(c.basePath.luminance, 12);
      expect(c.ab.absDiff, `${c.id} abs diff`).toBe(0);
      expect(c.ab.relativeError, `${c.id} rel diff`).toBe(0);
      expect(Math.abs(c.ab.lobeDeltaFromNeutral), `${c.id} lobe delta`).toBeGreaterThan(0.01);
    }
  });

  it('covers clearcoat, sheen, iridescence, and anisotropy in the fixture cases', () => {
    expect(fixture.coverage.specialtyLobes).toEqual([
      'anisotropy',
      'clearcoat',
      'iridescence',
      'sheen',
    ]);
    expect(fixture.cases.map((c) => [c.id, c.activeLobes])).toEqual([
      ['clearcoat-sheen', ['clearcoat', 'sheen']],
      ['iridescent-anisotropic', ['iridescence', 'anisotropy']],
      ['all-specialty-lobes', ['clearcoat', 'sheen', 'iridescence', 'anisotropy']],
    ]);
  });

  it('pins WGSL coverage from producer payload through reservoir serialization and resolve', () => {
    for (const line of [
      'var clearcoatV = clamp(vMat.clearcoat * sampleClearcoatTexture',
      'var sheenV = vMat.sheen;',
      'var iridescenceV = clamp(vMat.iridescence * sampleIridescenceTexture',
      'let anisotropyV = materialAnisotropy(vMatId, vHit.triIndex, vHit.baryVW);',
      'let wiRecon = rptSampleSourceReconnectionDirection(',
      'let pdfSrc = rptSourceDirectionalPdfFull(',
      'let pHat = restirPtTargetForDomain(r, woV, xs, Lo);',
    ]) {
      expect(RESTIR_PT_PRODUCER_WGSL).toContain(line);
    }

    for (const line of [
      'clearcoatV:        f32,',
      'sheenV:            f32,',
      'iridescenceV:      f32,',
      'anisotropyV:       f32,',
      'buf[b + 31u] = bitcast<u32>(r.clearcoatV);',
      'buf[b + 38u] = bitcast<u32>(r.iridescenceV);',
      'buf[b + 42u] = bitcast<u32>(r.anisotropyV);',
    ]) {
      expect(RESERVOIR_PT_HERO_WGSL).toContain(line);
    }

    for (const line of [
      'r.clearcoatV, r.clearcoatRoughnessV, r.sheenV, r.sheenRoughnessV, r.sheenColorV,',
      'r.iridescenceV, r.iridescenceIorV, r.iridescenceThicknessMinV, r.iridescenceThicknessMaxV,',
      'r.anisotropyV, r.anisotropyRotationV,',
      'let indirect = fBsdf * cosTheta * r.Lo * r.W;',
    ]) {
      expect(RESTIR_PT_RESOLVE_WGSL).toContain(line);
    }
  });
});
