import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const checkStatusPath = join(repoRoot, 'tools', 'learned-systems', 'check-status.mjs');
const statusPath = join(repoRoot, 'tools', 'learned-systems', 'learned-systems-status.json');
const packagePath = join(repoRoot, 'package.json');

test('learned systems status artifact reports stable runtimes and factual model provisioning', async () => {
  const status = JSON.parse(await readFile(statusPath, 'utf8'));
  assert.equal(status.schema, 'vitrum.learned-systems.status.v1');
  assert.equal(status.verdict, 'PASS');
  assert.equal(status.productionPosture, 'stable-host-certified-model-required');
  assert.equal(status.neuralDenoiser.implementationStatus, 'stable');
  assert.equal(status.neuralDenoiser.modelProvisioning, 'host-supplied-certified');
  assert.equal(status.neuralDenoiser.productionCheckpoint, null);
  assert.equal(status.neuralDenoiser.productionDefaultEligible, false);
  assert.equal(status.neuralDenoiser.packageProvidesProductionWeights, false);
  assert.equal(status.neuralDenoiser.productionCheckpointCount, 0);
  assert.equal(status.neuralDenoiser.researchCheckpointCount, 2);
  assert.deepEqual(status.neuralDenoiser.runtimePolicy, {
    autoSelectsNeuralOnlyWithProductionCheckpoint: true,
    explicitNeuralWithUncertifiedWeights: 'rejected',
    uncertifiedCapabilitySupport: 'unsupported',
    requiredMetadataContract: 'NeuralCheckpointMetadata',
  });
  assert.deepEqual(status.neuralDenoiser.qualityManifestRequirements, {
    manifestPath: 'tools/neural-denoiser-training/quality-ab-production.json',
    requiredVerdict: 'PASS',
    requiredMode: 'production-neural-denoiser',
    minSampleCount: 500,
    noisySpp: 1,
    minCleanReferenceSpp: 4096,
    requiresAlbedo: true,
    requiresNormals: true,
    requiresCaptureSource: true,
    requiresTonemap: true,
    requiresArtifacts: true,
    requiresArtifactFiles: true,
    requiresHardware: true,
    requiresGeneratedAt: true,
    requiresCheckpointIdentity: true,
    requiresComparison: true,
    requiresThresholds: true,
  });
  assert.equal(status.nrc.defaultEnabled, false);
  assert.equal(status.nrc.implementationStatus, 'stable');
  assert.equal(status.nrc.estimator, 'biased');
  assert.equal(status.nrc.productionDefaultEligible, false);
  assert.equal(status.nrc.qualityManifest, null);
  assert.equal(status.nrc.qualityManifestRequirements.manifestPath, "tools/learned-systems/nrc-quality-convergence.json");
  assert.equal(status.nrc.qualityManifestRequirements.requiresDefaultTierDecision, true);
  assert.equal(status.gris.defaultEnabled, false);
  assert.equal(status.gris.implementationStatus, 'stable');
  assert.equal(status.gris.optInFlag, 'grisReuse');
  assert.equal(status.gris.estimator, 'biased-ddgi-proxy');
  assert.equal(status.gris.productionDefaultEligible, false);
  assert.equal(status.gris.qualityManifest, null);
  assert.equal(status.gris.qualityManifestRequirements.manifestPath, "tools/learned-systems/gris-ddgi-proxy-quality.json");
  assert.equal(status.gris.qualityManifestRequirements.requiresProxyQualityComparison, true);
  assert.match(status.gris.optionalEvidence, /not a runtime-completeness gate/);
  assert.equal(status.ppg.defaultEnabled, false);
  assert.equal(status.ppg.implementationStatus, 'stable');
  assert.equal(status.ppg.estimator, 'defensive-mixture-guided');
  assert.equal(status.ppg.productionDefaultEligible, false);
  assert.equal(status.ppg.qualityManifest, null);
  assert.equal(status.ppg.qualityManifestRequirements.manifestPath, "tools/learned-systems/ppg-favorable-scene-ab.json");
  assert.equal(status.ppg.qualityManifestRequirements.requiresFavorableSceneAB, true);
  assert.ok(
    status.guardrails.some((entry) => /Do not treat this PASS as production model quality/.test(entry)),
    'status must keep the production-quality caveat',
  );
});

test('learned systems status is generated by an explicit write-status command', async () => {
  const source = await readFile(checkStatusPath, 'utf8');
  assert.match(source, /qualityManifestValidator\.mjs/);
  assert.match(source, /MIN_PRODUCTION_NEURAL_SAMPLE_COUNT/);
  assert.match(source, /MIN_PRODUCTION_NEURAL_CLEAN_REFERENCE_SPP/);
  assert.match(source, /function productionQualityRequirements/);
  assert.match(source, /function learnedPromotionQualityRequirements/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.nrc/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.gris/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.ppg/);
  assert.match(source, /artifactPathExists\(expectedRequirements\.manifestPath\)/);
  const qualityValidatorSource = await readFile(
    join(repoRoot, 'tools', 'learned-systems', 'qualityManifestValidator.mjs'),
    'utf8',
  );
  assert.match(qualityValidatorSource, /validateProductionDatasetManifest\(datasetManifest, datasetRecord, fail, artifactExists\)/);
  assert.match(qualityValidatorSource, /must point at an existing artifact/);
  assert.match(source, /qualityManifest is null while/);
  assert.match(source, /validate the manifest and update the status artifact before it can count/);
  assert.match(source, /requires production checkpoint thresholds before auto-selecting neural/);
  assert.match(source, /expect\(engine\.capabilities\.supportDetails\?\.denoisers\.neural\)\.toBe\('unsupported'\)/);
  assert.match(source, /await assertCommittedStatusArtifact/);
  assert.match(source, /const STATUS_PATH = "tools\/learned-systems\/learned-systems-status\.json"/);
  assert.match(source, /const WRITE_STATUS = Deno\.args\.includes\("--write-status"\)/);
  assert.match(source, /await Deno\.writeTextFile\(STATUS_PATH/);
  assert.match(source, /"stable-host-certified-model-required"/);

  const pkg = JSON.parse(await readFile(packagePath, 'utf8'));
  assert.match(pkg.scripts['learned-systems-status'], /--write-status/);
  assert.match(pkg.scripts['learned-systems-status'], /--allow-write=tools\/learned-systems\/learned-systems-status\.json/);
});
