import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const checkStatusPath = join(repoRoot, 'tools', 'learned-systems', 'check-status.mjs');
const statusPath = join(repoRoot, 'tools', 'learned-systems', 'learned-systems-status.json');
const queuePath = join(repoRoot, 'tools', 'road-to-100', 'validation-queue.json');
const packagePath = join(repoRoot, 'package.json');

test('learned systems status artifact stays explicitly non-production until provisioned', async () => {
  const status = JSON.parse(await readFile(statusPath, 'utf8'));
  assert.equal(status.schema, 'vitrum.learned-systems.status.v1');
  assert.equal(status.verdict, 'PASS');
  assert.equal(status.productionPosture, 'provisioning-needed');
  assert.equal(status.neuralDenoiser.productionCheckpoint, null);
  assert.equal(status.neuralDenoiser.productionDefaultEligible, false);
  assert.equal(status.neuralDenoiser.packageProvidesProductionWeights, false);
  assert.equal(status.neuralDenoiser.productionCheckpointCount, 0);
  assert.equal(status.neuralDenoiser.researchCheckpointCount, 2);
  assert.deepEqual(status.neuralDenoiser.qualityManifestRequirements, {
    manifestPath: 'tools/neural-denoiser-training/quality-ab-production.json',
    requiredVerdict: 'PASS',
    requiredMode: 'production-neural-denoiser',
    minSampleCount: 500,
    noisySpp: 1,
    minCleanReferenceSpp: 4096,
    requiresAlbedo: true,
    requiresNormals: true,
    requiresCaptureSource: true,
    requiresTonemap: true,
    requiresArtifacts: true,
    requiresArtifactFiles: true,
    requiresHardware: true,
    requiresGeneratedAt: true,
    requiresCheckpointIdentity: true,
    requiresComparison: true,
    requiresThresholds: true,
  });
  assert.equal(status.nrc.defaultEnabled, false);
  assert.equal(status.nrc.estimator, 'biased');
  assert.equal(status.nrc.productionDefaultEligible, false);
  assert.equal(status.nrc.qualityManifest, null);
  assert.equal(status.nrc.qualityManifestRequirements.manifestPath, "tools/learned-systems/nrc-quality-convergence.json");
  assert.equal(status.nrc.qualityManifestRequirements.requiresDefaultTierDecision, true);
  assert.equal(status.gris.defaultEnabled, false);
  assert.equal(status.gris.optInFlag, 'restirPtReuse');
  assert.equal(status.gris.estimator, 'unbiased-when-enabled');
  assert.equal(status.gris.productionDefaultEligible, false);
  assert.equal(status.gris.qualityManifest, null);
  assert.equal(status.gris.qualityManifestRequirements.manifestPath, "tools/learned-systems/gris-unbiasedness-ab.json");
  assert.equal(status.gris.qualityManifestRequirements.requiresUnbiasednessAB, true);
  assert.match(status.gris.remaining, /GRIS-on unbiasedness A\/B/);
  assert.equal(status.ppg.defaultEnabled, false);
  assert.equal(status.ppg.productionDefaultEligible, false);
  assert.equal(status.ppg.qualityManifest, null);
  assert.equal(status.ppg.qualityManifestRequirements.manifestPath, "tools/learned-systems/ppg-favorable-scene-ab.json");
  assert.equal(status.ppg.qualityManifestRequirements.requiresFavorableSceneAB, true);
  assert.ok(
    status.guardrails.some((entry) => /Do not treat this PASS as production model quality/.test(entry)),
    'status must keep the production-quality caveat',
  );
});

test('learned systems status is generated by an explicit write-status command', async () => {
  const source = await readFile(checkStatusPath, 'utf8');
  assert.match(source, /qualityManifestValidator\.mjs/);
  assert.match(source, /MIN_PRODUCTION_NEURAL_SAMPLE_COUNT/);
  assert.match(source, /MIN_PRODUCTION_NEURAL_CLEAN_REFERENCE_SPP/);
  assert.match(source, /function productionQualityRequirements/);
  assert.match(source, /function learnedPromotionQualityRequirements/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.nrc/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.gris/);
  assert.match(source, /qualityManifestRequirements: learnedRequirements.ppg/);
  assert.match(source, /artifactPathExists\(expectedRequirements\.manifestPath\)/);
  assert.match(source, /qualityManifest is null while/);
  assert.match(source, /validate the manifest and update the status artifact before it can count/);
  assert.match(source, /requires production checkpoint thresholds before auto-selecting neural/);
  assert.match(source, /expect\(engine\.capabilities\.supportDetails\?\.denoisers\.neural\)\.toBe\('approximate'\)/);
  assert.match(source, /await assertCommittedStatusArtifact/);
  assert.match(source, /const STATUS_PATH = "tools\/learned-systems\/learned-systems-status\.json"/);
  assert.match(source, /const WRITE_STATUS = Deno\.args\.includes\("--write-status"\)/);
  assert.match(source, /await Deno\.writeTextFile\(STATUS_PATH/);
  assert.match(source, /productionPosture: hasProductionCheckpoint \? "quality-gated" : "provisioning-needed"/);

  const pkg = JSON.parse(await readFile(packagePath, 'utf8'));
  assert.match(pkg.scripts['learned-systems-status'], /--write-status/);
  assert.match(pkg.scripts['learned-systems-status'], /--allow-write=tools\/learned-systems\/learned-systems-status\.json/);
});

test('learned systems Road row cites the committed status artifact', async () => {
  const queue = JSON.parse(await readFile(queuePath, 'utf8'));
  const row = queue.validationQueue.find((candidate) => candidate.id === 'VQ-LEARNED-SYSTEMS');
  assert.ok(row, 'VQ-LEARNED-SYSTEMS row should exist');
  const artifact = row.proofArtifacts.find((candidate) =>
    candidate.path === 'tools/learned-systems/learned-systems-status.json'
  );
  assert.ok(artifact, 'learned systems row should cite learned-systems-status.json');
  const paths = row.proofArtifacts.map((candidate) => candidate.path);
  assert.ok(paths.includes('tools/learned-systems/qualityManifestValidator.mjs'));
  assert.ok(paths.includes('scripts/__tests__/learned-systems-quality-manifest.test.mjs'));
  assert.deepEqual(artifact.json, {
    verdict: 'PASS',
    productionPosture: 'provisioning-needed',
    'neuralDenoiser.productionCheckpoint': null,
    'neuralDenoiser.productionDefaultEligible': false,
    'neuralDenoiser.packageProvidesProductionWeights': false,
    'neuralDenoiser.qualityManifestRequirements.manifestPath': 'tools/neural-denoiser-training/quality-ab-production.json',
    'neuralDenoiser.qualityManifestRequirements.minSampleCount': 500,
    'neuralDenoiser.qualityManifestRequirements.noisySpp': 1,
    'neuralDenoiser.qualityManifestRequirements.minCleanReferenceSpp': 4096,
    'neuralDenoiser.qualityManifestRequirements.requiresAlbedo': true,
    'neuralDenoiser.qualityManifestRequirements.requiresNormals': true,
    'neuralDenoiser.qualityManifestRequirements.requiresCaptureSource': true,
    'neuralDenoiser.qualityManifestRequirements.requiresTonemap': true,
    'neuralDenoiser.qualityManifestRequirements.requiresArtifacts': true,
    'neuralDenoiser.qualityManifestRequirements.requiresArtifactFiles': true,
    'neuralDenoiser.qualityManifestRequirements.requiresCheckpointIdentity': true,
    'nrc.defaultEnabled': false,
    'nrc.productionDefaultEligible': false,
    'nrc.qualityManifest': null,
    'nrc.qualityManifestRequirements.manifestPath': 'tools/learned-systems/nrc-quality-convergence.json',
    'nrc.qualityManifestRequirements.requiresDefaultTierDecision': true,
    'gris.defaultEnabled': false,
    'gris.productionDefaultEligible': false,
    'gris.qualityManifest': null,
    'gris.qualityManifestRequirements.manifestPath': 'tools/learned-systems/gris-unbiasedness-ab.json',
    'gris.qualityManifestRequirements.requiresUnbiasednessAB': true,
    'ppg.defaultEnabled': false,
    'ppg.productionDefaultEligible': false,
    'ppg.qualityManifest': null,
    'ppg.qualityManifestRequirements.manifestPath': 'tools/learned-systems/ppg-favorable-scene-ab.json',
    'ppg.qualityManifestRequirements.requiresFavorableSceneAB': true,
  });
});
