import { describe, expect, it } from 'vitest';

import { TRANSPARENT_OIT_MODULE, TRANSPARENT_OIT_WGSL } from '../shaders/transparentOit.wgsl.js';

describe('transparent OIT material parity', () => {
  it('shades camera-visible blend layers with extension-aware material BRDFs for sky, sun, point/spot, and finite emitters', () => {
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitLayerRadiance(hit: IntersectionResult, hitPos: vec3f, rayDir: vec3f, materialWord: u32) -> vec3f');
    expect(TRANSPARENT_OIT_WGSL).toContain('let payload = sampleRestirDIMaterialPayloadForHit(hit, normals.smoothNormal, normal, scalarBase, materialWord);');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitLayerSkyRadiance(payload: RestirDIMaterialPayload, normal: vec3f, wo: vec3f) -> vec3f');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitLayerEnvSampleRadiance(');
    expect(TRANSPARENT_OIT_WGSL).toContain('light for both HDRI-backed scenes and no-HDRI scalar/procedural sky fallback.');
    expect(TRANSPARENT_OIT_WGSL).toContain('let d1 = oitEnvSampleDir(normal,  0.70,  0.00);');
    expect(TRANSPARENT_OIT_WGSL).toContain('return avg * (2.0 * PI / 5.0);');
    expect(TRANSPARENT_OIT_WGSL).toContain('let skyAmbient = oitLayerSkyRadiance(payload, normal, wo);');
    expect(TRANSPARENT_OIT_WGSL).toContain('let sunBrdf = evalGGXWithSpecularClearcoatSheenWithAnisotropyFrame(');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.specular.rgb,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.anisotropy.x,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.anisotropyTangent,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.anisotropyBitangent,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.iridescence,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.clearcoatNormal,');
    expect(TRANSPARENT_OIT_WGSL).toContain('payload.sheen.rgb,');
    expect(TRANSPARENT_OIT_WGSL).toContain('let toSun = safe_normalize(ubo.sunDirection);');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitShadowTransmittance(origin: vec3f, dir: vec3f, tMax: f32, triEps: f32) -> f32');
    expect(TRANSPARENT_OIT_WGSL).toContain('return traceSceneAlphaTransmittanceTextured(');
    expect(TRANSPARENT_OIT_WGSL).toContain('true,');
    expect(TRANSPARENT_OIT_WGSL).toContain('bvh_material,');
    expect(TRANSPARENT_OIT_WGSL).toContain('BVH_MATERIAL_TEX_WIDTH,');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('fn oitCastsShadow(');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('fn oitHitIsScalarGlass(');
    expect(TRANSPARENT_OIT_WGSL).toContain('hitPos + hit.normal * 1e-3,');
    expect(TRANSPARENT_OIT_WGSL).toContain('sunVisibility = oitShadowTransmittance(');
    expect(TRANSPARENT_OIT_WGSL).toContain('let sunDirect = vec3f(ubo.sunIntensity) * sunBrdf * sunVisibility;');
    expect(TRANSPARENT_OIT_WGSL).toContain('@group(1) @binding(13) var analytic_lights: texture_2d<f32>;');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitLayerAnalyticNEE(');
    expect(TRANSPARENT_OIT_WGSL).toContain('let analyticHeader = textureLoad(analytic_lights, vec2i(0, 0), 0);');
    expect(TRANSPARENT_OIT_WGSL).toContain('let count = u32(max(analyticHeader.x, 0.0));');
    expect(TRANSPARENT_OIT_WGSL).toContain('let castShadowDisabled = light3.y > 0.5;');
    expect(TRANSPARENT_OIT_WGSL).toContain('if (!castShadowDisabled) {');
    expect(TRANSPARENT_OIT_WGSL).toContain('hitPos + geoNormal * 1e-3,');
    expect(TRANSPARENT_OIT_WGSL).toContain('shadowT = oitShadowTransmittance(');
    expect(TRANSPARENT_OIT_WGSL).toContain('let invDist2 = 1.0 / (dist * dist + ubo.emitterDist2Floor);');
    expect(TRANSPARENT_OIT_WGSL).toContain('Lo += lightLe * brdf * nDotL * cone * invDist2 * shadowT;');
    expect(TRANSPARENT_OIT_WGSL).toContain('let analyticDirect = oitLayerAnalyticNEE(hitPos, normal, payload.clearcoatNormal, hit.normal, payload, wo);');
    expect(TRANSPARENT_OIT_WGSL).toContain('@group(1) @binding(3) var<storage, read> emitters:     array<EmitterTri>;');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitLayerAreaEmitterNEE(');
    expect(TRANSPARENT_OIT_WGSL).toContain('const OIT_AREA_EMITTER_SAMPLE_COUNT = 4u;');
    expect(TRANSPARENT_OIT_WGSL).toContain('fn oitAreaEmitterXi(sampleIndex: u32) -> vec2f');
    expect(TRANSPARENT_OIT_WGSL).toContain('for (var si = 0u; si < OIT_AREA_EMITTER_SAMPLE_COUNT; si = si + 1u)');
    expect(TRANSPARENT_OIT_WGSL).toContain('let count = min(ubo.emitterCount, arrayLength(&emitters));');
    expect(TRANSPARENT_OIT_WGSL).toContain('let ls = sampleEmitterPoint(e, xi);');
    expect(TRANSPARENT_OIT_WGSL).toContain('let nlDotL = max(0.0, dot(-ls.normal, wi));');
    expect(TRANSPARENT_OIT_WGSL).toContain('shadowT = oitShadowTransmittance(');
    expect(TRANSPARENT_OIT_WGSL).toContain('let G = emitterGeometry(nlDotL, dist2, ubo.emitterDist2Floor);');
    expect(TRANSPARENT_OIT_WGSL).toContain('let Le = sampleEmitterLeAtXi(e, xi);');
    expect(TRANSPARENT_OIT_WGSL).toContain('Lo += Le * brdf * G * ls.area * shadowT * sampleWeight;');
    expect(TRANSPARENT_OIT_WGSL).toContain('let areaDirect = oitLayerAreaEmitterNEE(hitPos, normal, payload.clearcoatNormal, hit.normal, payload, wo);');
    expect(TRANSPARENT_OIT_WGSL).toContain('return (skyAmbient + sunDirect + analyticDirect + areaDirect) * viewFacing + emissive + baked;');
    expect(TRANSPARENT_OIT_WGSL).toContain('let hitPos = walkRay.origin + walkRay.direction * hit.dist;');
    expect(TRANSPARENT_OIT_WGSL).toContain('oitLayerRadiance(hit, hitPos, primaryRay.direction, word);');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('sunDiffuse');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('vec3f(ubo.sunIntensity) * albedo * INV_PI');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('let skyAmbient = envRadiance(normal) * payload.albedo * INV_PI;');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('if (!envHasMap()) {');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('return envRadiance(normal) * max(payload.envMapIntensity, 0.0) * payload.albedo * INV_PI;');
    expect(TRANSPARENT_OIT_WGSL).not.toContain('sunVisibility = select(1.0, 0.0, sunOccluded);');
  });

  it('keeps camera-visible emissive/light-map terms while declaring BRDF dependencies', () => {
    expect(TRANSPARENT_OIT_WGSL).toContain('sampleEmissiveMap(');
    expect(TRANSPARENT_OIT_WGSL).toContain('sampleLightMap(');
    expect(TRANSPARENT_OIT_MODULE.requires).toContain('materialAtlas');
    expect(TRANSPARENT_OIT_MODULE.requires).toContain('ggxBrdf');
    expect(TRANSPARENT_OIT_MODULE.requires).toContain('emitterLeAtXi');
  });
});
