/** AUTO-GENERATED by tools/generate-wgsl-layouts.mjs */
export const RC_PARAMS_BYTE_SIZE = 64;

export const RCParamsOffset = {
  probeOriginWorld: 0,
  rcWeight: 12,
  roomSize: 16,
  enabled: 28,
  probeCount: 32,
  raysPerProbe: 44,
  rayGridSize: 48,
} as const;

/** Byte size of one `RCLight` entry (mirrors probeRayCast.wgsl.ts). */
export const RC_LIGHT_ENTRY_BYTES = 64;

/** Byte size of the runtime `RCLightBuffer` header section. */
export const RC_LIGHTS_HEADER_BYTES = 16;

/** Byte size of one Walker/Vose alias entry (q, alias, represented PMF, pad). */
export const RC_LIGHT_ALIAS_ENTRY_BYTES = 16;

/** Smallest valid runtime light buffer: a header with count=0. */
export const RC_LIGHTS_BUFFER_BYTES = RC_LIGHTS_HEADER_BYTES;
export const RC_LIGHTS_ABI_MAGIC = 0x31544352;

/** Byte offsets within the `RCLightBuffer` header. */
export const RCLightBufferHeaderOffset = {
  count: 0,
  entriesWordOffset: 4,
  aliasWordOffset: 8,
  abiMagic: 12,
} as const;

/** Field byte offsets within one `RCLight` entry (relative to entry start). */
export const RCLightEntryOffset = {
  kind: 0,
  distance: 4,
  decay: 8,
  position: 16,
  intensity: 28,
  direction: 32,
  innerCone: 44,
  color: 48,
  outerCone: 60,
} as const;
