/** AUTO-GENERATED by tools/generate-wgsl-layouts.mjs */
export const RC_PARAMS_BYTE_SIZE = 64;

export const RCParamsOffset = {
  probeOriginWorld: 0,
  rcWeight: 12,
  roomSize: 16,
  enabled: 28,
  probeCount: 32,
  raysPerProbe: 44,
  rayGridSize: 48,
} as const;
