/**
 * svgfRealBindings.ts — TypeScript helpers for the real Schied 2017 SVGF pipeline.
 *
 * Provides typed UBO structs and ArrayBuffer packers for the three new SVGF
 * compute passes (reprojection, variance-from-moments, 7×7 spatial fallback).
 *
 * std140 layout rules apply: each field is 4-byte aligned; structs are
 * padded to a multiple of 16 bytes.
 *
 * W2-C13 follow-up: the hand-rolled `XXX_SIZE_BYTES` + `packXxxUniforms`
 * pair is generated by `defineUbo` (single source of truth — see
 * `@vitrum/shared-samplers/uboCodegen`). The previous layout (sigmaDepth @0,
 * sigmaNormal @4, alphaMin @8, _pad @12) is preserved in size; the old pad slot
 * now carries `forceReset` so hosts can deliberately discard reprojection
 * history on scene/lighting mutations without changing the binding size.
 */

import { defineUbo } from '@vitrum/shared-samplers';
import { ATROUS_VARIANCE_DEFAULT_ATROUS_UNIFORMS } from './atrousVarianceBindings.js';
import {
  SVGF_REAL_DEFAULT_ALPHA_MIN,
  SVGF_REAL_DEFAULT_SIGMA_DEPTH,
  SVGF_REAL_DEFAULT_SIGMA_NORMAL,
} from './svgfRealConstants.js';

// ============================================================
// SVGFReprojUBO — reprojection + EMA tuning
// ============================================================

export interface SVGFReprojUniforms {
  /** σ_z: max relative depth deviation for disocclusion test (Schied Eq. 2). Default 0.10. */
  readonly sigmaDepth: number;
  /** σ_n: minimum normal dot-product for acceptance (Schied Eq. 2). Default 0.95. */
  readonly sigmaNormal: number;
  /** α_min: minimum EMA weight (Schied Eq. 4). Default 0.05. */
  readonly alphaMin: number;
  /** Non-zero forces history rejection for this dispatch. Defaults to 0. */
  readonly forceReset?: number;
}

/**
 * SVGFReprojUBO codegen — single source of truth for size, layout, and pack.
 *
 * Field order matches the pre-codegen DataView writes at offsets 0/4/8; the
 * trailing 4-byte slot remains at offset 12 and now stores `forceReset`.
 */
const SVGF_REPROJ_UBO = defineUbo([
  { name: 'sigmaDepth',  type: 'f32' },
  { name: 'sigmaNormal', type: 'f32' },
  { name: 'alphaMin',    type: 'f32' },
  { name: 'forceReset',  type: 'u32' },
] as const);

/**
 * SVGFReprojUBO byte size — derived from the codegen layout.
 *
 * Layout (preserved byte-identically from the pre-codegen hand-roll):
 *   offset 0  — sigmaDepth  : f32  (4 bytes)
 *   offset 4  — sigmaNormal : f32  (4 bytes)
 *   offset 8  — alphaMin    : f32  (4 bytes)
 *   offset 12 — forceReset  : u32  (4 bytes; 0 = normal reprojection)
 * Total: 16 bytes.
 */
export const SVGF_REPROJ_UNIFORMS_SIZE_BYTES = SVGF_REPROJ_UBO.sizeBytes;

export const SVGF_REPROJ_DEFAULT_UNIFORMS: SVGFReprojUniforms = {
  sigmaDepth:  SVGF_REAL_DEFAULT_SIGMA_DEPTH,
  sigmaNormal: SVGF_REAL_DEFAULT_SIGMA_NORMAL,
  alphaMin:    SVGF_REAL_DEFAULT_ALPHA_MIN,
  forceReset:  0,
} as const;

/**
 * Pack SVGFReprojUniforms into an ArrayBuffer.
 *
 * @param u      - Uniform values to pack.
 * @param target - Destination ArrayBuffer (must be ≥ offset + SVGF_REPROJ_UNIFORMS_SIZE_BYTES).
 * @param offset - Byte offset into target (default: 0).
 */
export function packSVGFReprojUniforms(u: SVGFReprojUniforms, target: ArrayBuffer, offset = 0): void {
  const view = new DataView(target);
  SVGF_REPROJ_UBO.pack(view, offset, {
    sigmaDepth: u.sigmaDepth,
    sigmaNormal: u.sigmaNormal,
    alphaMin: u.alphaMin,
    forceReset: u.forceReset ?? 0,
  });
}

// ============================================================
// SVGF7x7FallbackUBO — 7×7 spatial-variance edge-stop tuning
// ============================================================

/**
 * Edge-stopping tuning for the 7×7 spatial variance fallback (Schied 2017 §4.3).
 *
 * The fallback estimates variance for newly-disoccluded pixels, where temporal
 * moments are not yet trustworthy. Both weights are the same quantities the
 * neighbouring passes already expose, so a host tuning the chain reaches this
 * pass too:
 *
 *  - `normalExponent` is the à-trous `sigmaNormal` — the exponent applied to the
 *    clamped normal dot product (`AtrousVarianceAtrousUniforms.sigmaNormal`).
 *  - `relativeDepthSigma` is the reprojection `sigmaDepth` — Schied Eq. 2 σ_z,
 *    a RELATIVE depth tolerance scaled by the larger sample depth. It is NOT the
 *    à-trous `sigmaDepth`, which scales a projected depth gradient instead and
 *    therefore carries a different default and a different unit.
 */
export interface SVGF7x7FallbackUniforms {
  /** σ_n exponent on `clamp(dot(n_center, n_sample), 0, 1)`. Default 128.0. */
  readonly normalExponent: number;
  /** σ_z relative depth tolerance (Schied Eq. 2). Default 0.10. */
  readonly relativeDepthSigma: number;
}

/**
 * SVGF7x7FallbackUBO codegen — single source of truth for size, layout, and pack.
 *
 * Layout:
 *   offset 0 — normalExponent     : f32 (4 bytes)
 *   offset 4 — relativeDepthSigma : f32 (4 bytes)
 * Total: 16 bytes (rounded up to the WebGPU minimum uniform-binding size;
 * `defineUbo.pack` zero-fills the trailing pad deterministically).
 *
 * The WGSL `struct SVGF7x7FallbackUBO` in wgsl/svgf7x7SpatialFallback.wgsl.ts
 * declares the same two f32 fields in this order.
 */
const SVGF_7X7_FALLBACK_UBO = defineUbo([
  { name: 'normalExponent',     type: 'f32' },
  { name: 'relativeDepthSigma', type: 'f32' },
] as const);

/** Byte size of the SVGF7x7FallbackUBO struct — derived from the codegen layout. */
export const SVGF_7X7_FALLBACK_UNIFORMS_SIZE_BYTES = SVGF_7X7_FALLBACK_UBO.sizeBytes;

/**
 * Defaults for the 7×7 spatial fallback.
 *
 * These are the values the pass previously folded in as WGSL constants, sourced
 * from the constants the sibling passes already default to, so an un-tuned host
 * renders exactly as before.
 */
export const SVGF_7X7_FALLBACK_DEFAULT_UNIFORMS: SVGF7x7FallbackUniforms = {
  normalExponent:     ATROUS_VARIANCE_DEFAULT_ATROUS_UNIFORMS.sigmaNormal,
  relativeDepthSigma: SVGF_REAL_DEFAULT_SIGMA_DEPTH,
} as const;

/**
 * Pack SVGF7x7FallbackUniforms into an ArrayBuffer.
 *
 * @param u      - Uniform values to pack.
 * @param target - Destination ArrayBuffer (must be ≥ offset + SVGF_7X7_FALLBACK_UNIFORMS_SIZE_BYTES).
 * @param offset - Byte offset into target (default: 0).
 */
export function packSVGF7x7FallbackUniforms(
  u: SVGF7x7FallbackUniforms,
  target: ArrayBuffer,
  offset = 0,
): void {
  const view = new DataView(target);
  SVGF_7X7_FALLBACK_UBO.pack(view, offset, {
    normalExponent:     u.normalExponent,
    relativeDepthSigma: u.relativeDepthSigma,
  });
}
