/**
 * svgfRealBindings.ts — TypeScript helpers for the real Schied 2017 SVGF pipeline.
 *
 * Provides typed UBO structs and ArrayBuffer packers for the three new SVGF
 * compute passes (reprojection, variance-from-moments, 7×7 spatial fallback).
 *
 * std140 layout rules apply: each field is 4-byte aligned; structs are
 * padded to a multiple of 16 bytes.
 *
 * W2-C13 follow-up: the hand-rolled `XXX_SIZE_BYTES` + `packXxxUniforms`
 * pair is generated by `defineUbo` (single source of truth — see
 * `@vitrum/shared-samplers/uboCodegen`). The previous layout (sigmaDepth @0,
 * sigmaNormal @4, alphaMin @8, _pad @12) is preserved byte-identically:
 * three f32 fields pack to bytes 0..11, and `defineUbo` zero-fills the
 * struct to the WebGPU 16-byte minimum-binding floor.
 */

import { defineUbo } from '@vitrum/shared-samplers';
import {
  SVGF_REAL_DEFAULT_ALPHA_MIN,
  SVGF_REAL_DEFAULT_SIGMA_DEPTH,
  SVGF_REAL_DEFAULT_SIGMA_NORMAL,
} from './svgfRealConstants.js';

// ============================================================
// SVGFReprojUBO — reprojection + EMA tuning
// ============================================================

export interface SVGFReprojUniforms {
  /** σ_z: max relative depth deviation for disocclusion test (Schied Eq. 2). Default 0.10. */
  readonly sigmaDepth: number;
  /** σ_n: minimum normal dot-product for acceptance (Schied Eq. 2). Default 0.95. */
  readonly sigmaNormal: number;
  /** α_min: minimum EMA weight (Schied Eq. 4). Default 0.05. */
  readonly alphaMin: number;
}

/**
 * SVGFReprojUBO codegen — single source of truth for size, layout, and pack.
 *
 * Field order matches the pre-codegen DataView writes at offsets 0/4/8;
 * the trailing 4-byte _pad slot is produced by defineUbo's std140 round-up
 * to the 16-byte WebGPU minimum-binding size (no explicit `_pad` field
 * needed — pack() zero-fills the entire destination region first).
 */
const SVGF_REPROJ_UBO = defineUbo([
  { name: 'sigmaDepth',  type: 'f32' },
  { name: 'sigmaNormal', type: 'f32' },
  { name: 'alphaMin',    type: 'f32' },
] as const);

/**
 * SVGFReprojUBO byte size — derived from the codegen layout.
 *
 * Layout (preserved byte-identically from the pre-codegen hand-roll):
 *   offset 0  — sigmaDepth  : f32  (4 bytes)
 *   offset 4  — sigmaNormal : f32  (4 bytes)
 *   offset 8  — alphaMin    : f32  (4 bytes)
 *   offset 12 — _pad        : u32  (4 bytes — alignment; zero-filled by pack)
 * Total: 16 bytes.
 */
export const SVGF_REPROJ_UNIFORMS_SIZE_BYTES = SVGF_REPROJ_UBO.sizeBytes;

export const SVGF_REPROJ_DEFAULT_UNIFORMS: SVGFReprojUniforms = {
  sigmaDepth:  SVGF_REAL_DEFAULT_SIGMA_DEPTH,
  sigmaNormal: SVGF_REAL_DEFAULT_SIGMA_NORMAL,
  alphaMin:    SVGF_REAL_DEFAULT_ALPHA_MIN,
} as const;

/**
 * Pack SVGFReprojUniforms into an ArrayBuffer.
 *
 * @param u      - Uniform values to pack.
 * @param target - Destination ArrayBuffer (must be ≥ offset + SVGF_REPROJ_UNIFORMS_SIZE_BYTES).
 * @param offset - Byte offset into target (default: 0).
 */
export function packSVGFReprojUniforms(u: SVGFReprojUniforms, target: ArrayBuffer, offset = 0): void {
  const view = new DataView(target);
  SVGF_REPROJ_UBO.pack(view, offset, u);
}
